// src/components/sections/Presentation.svelte
<div class="Presentation" id="presentation">
    <div class="row">
        <div class="image">
            <img src="person.png" alt="">
        </div>
        <div class="text">
            <h2>Who Am I ?</h2>
            <p>
                I am currently studying Computer Science at the <a href="https://www.utbm.fr/" target="_blank">University of Technology of Belfort-Montbéliard (UTBM), in France</a>.
                I am passionate about software development and programming in general and love building tools that helps people.
            </p>
        </div>
        
    </div>
    <div class="row reverse">
        <div class="text">
            <h2>Programming languages and tools</h2>
            <p>
                During my studies and thanks to the different projects I have worked on, I have learned many technologies. I have mostly used <a href="https://en.wikipedia.org/wiki/Java_(programming_language)" target="_blank">Java</a> and
                <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language)" target="_blank">C#</a> to build applications but also more low-level languages such as <a href="https://en.wikipedia.org/wiki/The_C_Programming_Language" target="_blank">C</a> and <a href="https://en.wikipedia.org/wiki/C%2B%2B">C++</a>.
                I also know web technologies and have worked with <a href="https://en.wikipedia.org/wiki/Node.js" target="_blank">NodeJS</a>, <a href="https://en.wikipedia.org/wiki/React_(JavaScript_library)" target="_blank">React</a> and <a href="https://en.wikipedia.org/wiki/PHP" target="_blank">PHP</a>.
                I am used to version control tools such as <a href="https://en.wikipedia.org/wiki/Git" target="_blank">Git</a>.
            </p>
        </div>
        <div class="image swaped">
            <img src="coding.png" alt="">
        </div>
    </div>
    <div class="row skills">
        <a href=""><img src="https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=java&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/C%23-239120?style=for-the-badge&logo=c-sharp&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/C-00599C?style=for-the-badge&logo=c&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/C%2B%2B-00599C?style=for-the-badge&logo=c%2B%2B&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Python-14354C?style=for-the-badge&logo=python&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Sass-CC6699?style=for-the-badge&logo=sass&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Node.js-43853D?style=for-the-badge&logo=node.js&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Vue.js-35495E?style=for-the-badge&logo=vue.js&logoColor=4FC08D" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/PHP-777BB4?style=for-the-badge&logo=php&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Symfony-14354C?style=for-the-badge&logo=symfony&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/MySQL-00000F?style=for-the-badge&logo=mysql&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Neo4j-0186F7?style=for-the-badge&logo=neo4j&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Redis-D82C20?style=for-the-badge&logo=redis&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Docker-002C66.svg?style=for-the-badge&logo=docker&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Git-E74C3C?style=for-the-badge&logo=git&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Unity-100000?style=for-the-badge&logo=unity&logoColor=white" alt=""></a>
    </div>

    <div class="row">
        <div class="image">
            <img src="software.png" alt="">
        </div>
        <div class="text">
            <h2>Software</h2>
            <p>
               The operating system i am mainly working on is <a href="https://en.wikipedia.org/wiki/Windows_10" target="_blank">Windows 10</a> but I also have some knowledge with <a href="https://en.wikipedia.org/wiki/Ubuntu" target="_blank">Ubuntu</a>.
               For programming, I use a lot <a href="https://en.wikipedia.org/wiki/Visual_Studio_Code" target="_blank">Visual Studio Code</a> but also <a href="https://en.wikipedia.org/wiki/IntelliJ_IDEA" target="_blank">IntelliJ IDEA</a> and <a href="https://en.wikipedia.org/wiki/Eclipse_(software)" target="_blank">Eclipse</a>.
               I also have experience with the <a href="https://en.wikipedia.org/wiki/Microsoft_Office" target="_blank">Office suite</a>.
            </p>
        </div>
        
    </div>

    <div class="row skills">
        <a href=""><img src="https://img.shields.io/badge/Visual_Studio_Code-0078D4?style=for-the-badge&logo=visual%20studio%20code&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Visual_Studio-35294F?style=for-the-badge&logo=visual%20studio&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/IntelliJIDEA-000000.svg?style=for-the-badge&logo=intellij-idea&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Android_Studio-88BB56.svg?style=for-the-badge&logo=android%20studio&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Eclipse-2C2255?style=for-the-badge&logo=eclipse&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Github-000000?style=for-the-badge&logo=github&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Bitbucket-257CF1?style=for-the-badge&logo=bitbucket&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Jira-2684FF?style=for-the-badge&logo=jira&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Microsoft_Office-D54502?style=for-the-badge&logo=microsoft%20office&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Windows%2010-001A37?style=for-the-badge&logo=windows&logoColor=white" alt=""></a>
        <a href=""><img src="https://img.shields.io/badge/Ubuntu-DE4815?style=for-the-badge&logo=ubuntu&logoColor=white" alt=""></a>
        
    </div>
    
</div>

<style lang="scss" scoped>
    @use "../../styles/variables";

    .Presentation {
        min-height: 100vh;
        background-color: variables.$main_background_color;
        color: #FFF;
        padding-top: 10vh;
        display: flex;
        flex-direction: column;
        align-items: center;

        .row {
            display: flex;
            justify-content: center;
            margin-bottom: 50px;
            width: 50%;
            max-width: 50%;

            @media(max-width: 1100px) {
                flex-direction: column;
                width: 90%;
                max-width: 90%;
                align-items: center;;
            }

            &.reverse {
                    @media(max-width: 1100px) {
                        flex-direction: column-reverse;
                    }
            }
            
            &.skills {
                a {
                    margin-right: 5px;
                }

                text-align: center;
                display: inline-block;
            }

            .image {
                width: 30%;
                display: flex;
                align-items: center;
                
                @media(max-width: 1100px) {
                    justify-content: center;
                    margin-bottom: 20px;
                }

                &.swaped {
                    justify-content: right;

                    @media(max-width: 1100px) {
                        justify-content: center;
                    }
                }
                
                img {
                    width: 130px;
                }
            }

            .text {
                width: 100%;
                h2 {
                    color: variables.$green;
                    margin-bottom: 10px;
                }

                p {
                    line-height: 27px;
                    font-size: 15px;
                    text-align: justify;

                    a {
                        color: variables.$green;
                        text-decoration: none;
                    }
                }
            }
        }
    }
</style>

// src/views/sections/Presentation.vue
<template>
    <div class="Presentation" id="presentation">
        <div class="row">
            <div class="image">
                <img src="/assets/person.png" alt="">
            </div>
            <div class="text">
                <h2>Who Am I ?</h2>
                <p>
                    I am currently studying Computer Science at the <a href="https://www.utbm.fr/" target="_blank">University of Technology of Belfort-Montbéliard (UTBM), in France</a>.
                    I am passionate about software development and programming in general and love building tools that helps people.
                </p>
            </div>
            
        </div>
        <div class="row reverse">
            <div class="text">
                <h2>Programming languages and tools</h2>
                <p>
                    During my studies and thanks to the different projects I have worked on, I have learned many technologies. I have mostly used <a href="https://en.wikipedia.org/wiki/Java_(programming_language)" target="_blank">Java</a> and
                    <a href="https://en.wikipedia.org/wiki/C_Sharp_(programming_language)" target="_blank">C#</a> to build applications but also more low-level languages such as <a href="https://en.wikipedia.org/wiki/The_C_Programming_Language" target="_blank">C</a> and <a href="https://en.wikipedia.org/wiki/C%2B%2B">C++</a>.
                    I also know web technologies and have worked with <a href="https://en.wikipedia.org/wiki/Node.js" target="_blank">NodeJS</a>, <a href="https://en.wikipedia.org/wiki/React_(JavaScript_library)" target="_blank">React</a> and <a href="https://en.wikipedia.org/wiki/PHP" target="_blank">PHP</a>.
                    I am used to version control tools such as <a href="https://en.wikipedia.org/wiki/Git" target="_blank">Git</a>.
                </p>
            </div>
            <div class="image swaped">
                <img src="/assets/coding.png" alt="">
            </div>
        </div>
        <div class="row skills">
            <a href=""><img src="https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=java&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/C%23-239120?style=for-the-badge&logo=c-sharp&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/C-00599C?style=for-the-badge&logo=c&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/C%2B%2B-00599C?style=for-the-badge&logo=c%2B%2B&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Python-14354C?style=for-the-badge&logo=python&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Sass-CC6699?style=for-the-badge&logo=sass&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Node.js-43853D?style=for-the-badge&logo=node.js&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Vue.js-35495E?style=for-the-badge&logo=vue.js&logoColor=4FC08D" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/PHP-777BB4?style=for-the-badge&logo=php&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Symfony-14354C?style=for-the-badge&logo=symfony&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/MySQL-00000F?style=for-the-badge&logo=mysql&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Neo4j-0186F7?style=for-the-badge&logo=neo4j&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Redis-D82C20?style=for-the-badge&logo=redis&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Docker-002C66.svg?style=for-the-badge&logo=docker&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Git-E74C3C?style=for-the-badge&logo=git&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Unity-100000?style=for-the-badge&logo=unity&logoColor=white" alt=""></a>
        </div>

        <div class="row">
            <div class="image">
                <img src="/assets/software.png" alt="">
            </div>
            <div class="text">
                <h2>Software</h2>
                <p>
                   The operating system i am mainly working on is <a href="https://en.wikipedia.org/wiki/Windows_10" target="_blank">Windows 10</a> but I also have some knowledge with <a href="https://en.wikipedia.org/wiki/Ubuntu" target="_blank">Ubuntu</a>.
                   For programming, I use a lot <a href="https://en.wikipedia.org/wiki/Visual_Studio_Code" target="_blank">Visual Studio Code</a> but also <a href="https://en.wikipedia.org/wiki/IntelliJ_IDEA" target="_blank">IntelliJ IDEA</a> and <a href="https://en.wikipedia.org/wiki/Eclipse_(software)" target="_blank">Eclipse</a>.
                   I also have experience with the <a href="https://en.wikipedia.org/wiki/Microsoft_Office" target="_blank">Office suite</a>.
                </p>
            </div>
            
        </div>

        <div class="row skills">
            <a href=""><img src="https://img.shields.io/badge/Visual_Studio_Code-0078D4?style=for-the-badge&logo=visual%20studio%20code&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Visual_Studio-35294F?style=for-the-badge&logo=visual%20studio&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/IntelliJIDEA-000000.svg?style=for-the-badge&logo=intellij-idea&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Android_Studio-88BB56.svg?style=for-the-badge&logo=android%20studio&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Eclipse-2C2255?style=for-the-badge&logo=eclipse&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Github-000000?style=for-the-badge&logo=github&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Bitbucket-257CF1?style=for-the-badge&logo=bitbucket&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Jira-2684FF?style=for-the-badge&logo=jira&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Microsoft_Office-D54502?style=for-the-badge&logo=microsoft%20office&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Windows%2010-001A37?style=for-the-badge&logo=windows&logoColor=white" alt=""></a>
            <a href=""><img src="https://img.shields.io/badge/Ubuntu-DE4815?style=for-the-badge&logo=ubuntu&logoColor=white" alt=""></a>
            
        </div>
        
    </div>
</template>

<script lang="ts">
export default {

}
</script>

<style lang="scss" scoped>
    @use "../../styles/variables";

    .Presentation {
        min-height: 100vh;
        background-color: variables.$main_background_color;
        color: #FFF;
        padding-top: 10vh;
        display: flex;
        flex-direction: column;
        align-items: center;

        .row {
            display: flex;
            justify-content: center;
            margin-bottom: 50px;
            width: 50%;
            max-width: 50%;

            @media(max-width: 1100px) {
                flex-direction: column;
                width: 90%;
                max-width: 90%;
                align-items: center;;
            }

            &.reverse {
                    @media(max-width: 1100px) {
                        flex-direction: column-reverse;
                    }
            }
            
            &.skills {
                a {
                    margin-right: 5px;
                }

                text-align: center;
                display: inline-block;
            }

            .image {
                width: 30%;
                display: flex;
                align-items: center;
                
                @media(max-width: 1100px) {
                    justify-content: center;
                    margin-bottom: 20px;
                }

                &.swaped {
                    justify-content: right;

                    @media(max-width: 1100px) {
                        justify-content: center;
                    }
                }
                
                img {
                    width: 130px;
                }
            }

            .text {
                width: 100%;
                h2 {
                    color: variables.$green;
                    margin-bottom: 10px;
                }

                p {
                    line-height: 27px;
                    font-size: 15px;
                    text-align: justify;

                    a {
                        color: variables.$green;
                        text-decoration: none;
                    }
                }
            }
        }
    }
</style>
